### ISSUE TITLE
Diff should consider pre only on greater version

### ISSUE THREAD

**Issue by mick62** [npm/node-semver#440] opened 2022-03-17 15:28 UTC
The "diff" function should report the level of the highest prio difference.
When comparing "1.1.1-foo" to "1.1.2" the fact that the first is a pre-build is not of interest because the second is a regular version, i.e. the relevant change is on patch level.
Hence the result should be "patch", not "prepatch".
When comparing "1.1.1" to "1.1.2-foo" the relevant change is on patch level but with the caveat that the second is a pre-release version.
Hence only in this case the result should be (as it is now) "prepatch".

**Comment by lukekarrys** [comment] 2022-04-10 05:38
Closing as a duplicate of #333.

**Closed by lukekarrys** 2022-04-10 05:38 UTC
