### ISSUE TITLE
[DOCS] How do I get to 1.0.0-5 using increments?

### ISSUE THREAD

**Issue by mik01aj** [npm/node-semver#124] opened 2015-04-08 14:49 UTC
I tried this:

```
> s = require('semver')
> v='0.0.0'
'0.0.0'
> v = s.inc(v, 'premajor')
'1.0.0-0'
> v = s.inc(v, 'premajor')
'2.0.0-0'
> v = s.inc(v, 'premajor')
'3.0.0-0'
> v = s.inc(v, 'premajor')
```

I would expect `1.0.0-0`, `1.0.0-1`, `1.0.0-2` and so on -- as I can have a number of pre-releases before I do `s.inc(v, 'major')`, right?

Is this just my misunderstanding or is it a bug? And if this behaviour is expected, how do I get to e.g. 1.0.0-5 using the `inc` function? Or should I use the **undocumented** `pre` option from https://github.com/npm/node-semver/blob/master/semver.js#L457 ?

Btw, the same applies to `inc` with `preminor` or `prepatch`.

**Comment by isaacs** [comment] 2015-04-08 16:30
Working as designed.  Doc patch welcome!

```
> v='0.0.0'
'0.0.0'
> v = s.inc(v, 'premajor')
'1.0.0-0'
> v = s.inc(v, 'pre')
'1.0.0-1'
> v = s.inc(v, 'pre')
'1.0.0-2'
> v = s.inc(v, 'pre')
'1.0.0-3'
> v = s.inc(v, 'pre')
'1.0.0-4'
> v = s.inc(v, 'pre')
'1.0.0-5'
```

**Comment by mik01aj** [comment] 2015-04-08 16:33
Ok, well, but then `pre` wasn't documented for a reason. Comment in the linked source:

    // This probably shouldn't be used publicly.
    // 1.0.0 "pre" would become 1.0.0-0 which is the wrong direction.

**Comment by isaacs** [comment] 2015-04-08 17:47
Hm.  That's a good point.  Maybe we could just include that caveat in the documentation for `inc(v,'pre')`?

**Comment by mbtools** [comment] 2023-06-21 07:12
Suggest closing this since you can use `prerelease` instead of undocumented `pre`:

```bash
> npx semver -i premajor 0.0.0    
1.0.0-0
> npx semver -i prerelease 1.0.0-0
1.0.0-1
> npx semver -i prerelease 1.0.0-1
1.0.0-2
```

**Comment by wraithgar** [comment] 2023-06-21 13:51
thank you @mbtools

**Closed by wraithgar** 2023-06-21 13:51 UTC
Labels: Needs Documentation
