### ISSUE TITLE
[BUG] diff('2.0.0-alpha.15', '2.0.0') returns prerelease when it should return major

### ISSUE THREAD

**Issue by lazd** [npm/node-semver#288] opened 2019-09-12 15:12 UTC
# What / Why
> A bump from an alpha of a major release to the actual major release is considered a prerelease by `diff` when it's actually a major release.

## When
* Always

## Where
* npm/semver

### Current Behavior
* `diff('2.0.0-alpha.15', '2.0.0')` returns `prerelease`

### Steps to Reproduce

```js
const semver = require('semver');
semver.diff('2.0.0-alpha.15', '2.0.0'); // == prerelease
```

### Expected Behavior

* `diff('2.0.0-alpha.15', '2.0.0')` returns `major`
* That is, the output of `diff('2.0.0-alpha.15', '2.0.0')` should be consistent with `inc('2.0.0-alpha.15', 'major')`.
* When we increment `2.0.0-alpha.15` by `major`, we get `2.0.0`, and when we diff `2.0.0-alpha.15` against `2.0.0`, we should also get `major`.

## Who
* n/a

## References
* #83 
* #111

**Comment by lukekarrys** [comment] 2022-04-10 05:32
Closing as a duplicate of #333 which we'll use to track this bug.

**Closed by lukekarrys** 2022-04-10 05:32 UTC
