### ISSUE TITLE
Require cycle warning

### ISSUE THREAD

**Issue by brunomartinezciompi** [npm/node-semver#398] opened 2021-09-01 18:49 UTC
Hey! I am getting this warning on the latest release. 

`Require cycle: node_modules/semver/classes/comparator.js -> node_modules/semver/classes/range.js -> node_modules/semver/classes/comparator.js`

I understand require cycles are allowed and this is just a warning, but it can result in uninitialized values, so it would be nice to get that fixed.

**Comment by RayVR** [comment] 2022-01-24 01:28
require cycles are technically allowed but should not be tolerated.

**Comment by lukekarrys** [comment] 2022-02-26 08:45
This is a duplicate of #318 and #381. I'm keeping #381 open as it has the most information about the issue.

**Closed by lukekarrys** 2022-02-26 08:45 UTC
