### ISSUE TITLE
Invalid semver version

### ISSUE THREAD

**Issue by AjiteshMDK** [npm/node-semver#429] opened 2022-02-12 07:42 UTC
Hello Nativescript Team, Hello @isaacs 

Can anyone please have a look into below issue and provide a solution? Please help.

[Git Link](https://github.com/AjiteshMDK/GeoLocation-Update)

<img width="487" alt="image" src="https://user-images.githubusercontent.com/86408441/153702163-c0437bae-28fc-4b5c-a085-599857c27a0b.png">

**Comment by lukekarrys** [comment] 2022-02-26 08:22
This is probably caused by #354. You can try deduping your package tree to a single instance of semver. Try using `npm ls semver` to see where it is in your tree. I'm going to close this and track in #354.

**Closed by lukekarrys** 2022-02-26 08:22 UTC
