### ISSUE TITLE
`.valid()` trims build metadata?..

### ISSUE THREAD

**Issue by busticated** [npm/node-semver#264] opened 2018-12-18 01:27 UTC
hey there :wave:

is this expected behavior?

```js
const semver = require('semver');
const version = '0.8.0-rc.27+test';

semver.valid(version); // => 0.8.0-rc.27
semver.parse(version); /* => 
SemVer {
  loose: undefined,
  raw: '0.8.0-rc.27+test',
  major: 0,
  minor: 8,
  patch: 0,
  prerelease: [ 'rc', 27 ],
  build: [ 'test' ],
  version: '0.8.0-rc.27' }
*/
```

i expected `.valid()` to return the full version including the build metadata (`0.8.0-rc.27+test`) and also for `.parse()` to include build metadata in the `version` field.

**Comment by octogonz** [comment] 2021-04-07 23:37
We are trying to implement a function that discards the build metadata suffix, like this:

`0.8.0-rc.27+test` --> `0.8.0-rc.27`

I expected to solve it like this:
```ts
const version = semver.parse("0.8.0-rc.27+test")
version.build = [] // discard the "+test" part
version.format()  // expected to print "0.8.0-rc.27"
```

But it seems that `format()` never includes the build metadata.  So technically I could skip the `version.build = []` step -- but is that safe?  Will the behavior get fixed in some future release of this library?  Or is the current behavior "by design"?

Similarly, as @busticated pointed out `semver.valid("0.8.0-rc.27+test")` can also solve this problem.  But can we safely rely on that? Or might it get fixed later?

The current API design does seem counterintuitive if not incorrect.

**Comment by octogonz** [comment] 2021-04-07 23:38
@isaacs are you the sole maintainer of this project?

**Comment by isaacs** [comment] 2021-09-28 22:48
This project is maintained by the @github/npm-cli team.

Node-semver has always stripped build metadata from the formatting functions, because it's not relevant to semver validity or precedence.  It's explicitly irrelevant for the purposes this library is concerned with, so it is not used.

If you just want to parse a version string and get the build metadata, ok, you can do that easily enough.

```
> semver.parse('1.2.3+build.metadata.1.2.3').build
[ 'build', 'metadata', '1', '2', '3' ]
```

We also discard some idiosyncrasies that are (or at least, were once) common in the JS ecosystem, such as a leading `v` or `=` at the start of a version number, and the presence of a `-` ahead of prerelease tags is optional when `{ loose: true }` is specified in the options.

```
> semver.parse('v1.2.3foo', { loose: true })
SemVer {
  options: { loose: true },
  loose: true,
  includePrerelease: false,
  raw: 'v1.2.3foo',
  major: 1,
  minor: 2,
  patch: 3,
  prerelease: [ 'foo' ],
  build: [],
  version: '1.2.3-foo'
}
```

The documentation states that `semver.valid()` will "return the parsed version, or null if it's not valid".  The contract is not "returns the string unmodified" - it returns a semver string which has an identical value, and is subject to the maximum level of strictness and interoperability.  If you want the original string, ok, well, you already have that, and it's also on the `raw` field of the object returned by `semver.parse()`.

**Closed by isaacs** 2021-09-28 22:48 UTC

**Comment by isaacs** [comment] 2021-09-28 22:49
> is that safe? Will the behavior get fixed in some future release of this library? Or is the current behavior "by design"?

Yes, it is very safe.  If that ever changes, it will be in a major version update to this library, which has not changed significantly in many years.  You can use `semver.valid(str)` to strip build metadata and get a maximally interoperable semver string for parseable semvers, and null if it does not parse properly.
