### ISSUE TITLE
[QUESTION] throw new TypeError('Invalid Version: ' + version)

### ISSUE THREAD

**Issue by JamesJoeLee** [npm/node-semver#384] opened 2021-05-20 11:02 UTC
# What / Why
An error was reported when npm run build. Error message:

E:\sources\MDIprograms\02 program\WEB\0519\test3\node_modules\semver\semver.js:323
    throw new TypeError('Invalid Version: ' + version)
    ^

TypeError: Invalid Version: 6.14.11
    at new SemVer (E:\sources\MDIprograms\02 program\WEB\0519\test3\node_modules\semver\semver.js:323:11)
    at Range.test (E:\sources\MDIprograms\02 program\WEB\0519\test3\node_modules\semver\semver.js:1203:15)
    at Function.satisfies (E:\sources\MDIprograms\02 program\WEB\0519\test3\node_modules\semver\semver.js:1257:16)
    at module.exports (E:\sources\MDIprograms\02 program\WEB\0519\test3\build\check-versions.js:33:17)
    at Object.<anonymous> (E:\sources\MDIprograms\02 program\WEB\0519\test3\build\build.js:2:28)

## Where
npm run build

## Who

* n/a

## References

* n/a

**Comment by lukekarrys** [comment] 2022-02-26 08:22
This is probably caused by #354. You can try deduping your package tree to a single instance of semver. Try using `npm ls semver` to see where it is in your tree. I'm going to close this and track in #354.

**Closed by lukekarrys** 2022-02-26 08:22 UTC
