### ISSUE TITLE
Possible parsing bug?

### ISSUE THREAD

**Issue by steveklabnik** [npm/node-semver#171] opened 2016-10-03 16:21 UTC
According to https://semver.npmjs.com/, 

`*.0` parses the same as `*`. Is this a bug? This matching `1.2.1` seems very strange.

**Comment by isaacs** [comment] 2016-10-03 18:54
This is an interesting question.

Were I to do this today, I'd say that `1.*.0` is an invalid range.  Anything coming after the `*` is dropped anyway, but we don't raise an error about it.

It's a little strange to think of this as a glob, because it's exceedingly bizarre to say "I want to accept any minor version bumps, but _not_ any patch releases".

Also, should `2.0.1` match `*.0`?  What about `1.2.0`?  Does the `*` apply to only one portion of the 3-ple, or more than one?

In practice, the parser stops at the first `*` or `x` that it finds.  So, it's by design that `*.0` is equivalent to `*`, but arguably that design is falling victim to some undefined behavior.

Dropping support for this would break some stuff in npm, so we haven't taken on the cost of figuring out how to best do that.  I'd recommend that any new implementations fail to parse `*.0`, unless they are similarly constrained.

**Comment by steveklabnik** [comment] 2016-10-03 18:59
Thanks. This seems exactly in line with what I'm thinking. Rust's semver implementation did the same thing, and unfortunately, we have a few packages in the registry that use it. So I'm currently going to still parse it as `*` with a warning.

**Comment by isaacs** [comment] 2016-10-03 20:34
Sounds good.  I'll close this issue, then, since there's no facility for node-semver to display warnings, and it's probably not worth adding one for this.

Doc patch welcome, tho, if you feel so inclined :)

Thanks!

**Closed by isaacs** 2016-10-03 20:34 UTC
